import type { FoundationState, VoteChoice } from './domain'

const members = [
  { id: 'elise', name: 'Elise', initials: 'EL', color: '#315f52' },
  { id: 'louis', name: 'Louis', initials: 'LB', color: '#a9623a' },
  { id: 'marie', name: 'Marie', initials: 'MD', color: '#7a5c8e' },
  { id: 'thomas', name: 'Thomas', initials: 'TB', color: '#4d6f91' },
  { id: 'sophie', name: 'Sophie', initials: 'SB', color: '#b47777' },
]

const votes = (choices: VoteChoice[]): Record<string, VoteChoice> =>
  Object.fromEntries(members.map((member, index) => [member.id, choices[index] ?? 'pending']))

export const createSeedState = (): FoundationState => ({
  familyName: 'Berghmans Family Foundation',
  mission:
    'We back proven, locally led solutions that give communities in the Great Lakes region lasting access to the foundations of a healthy life.',
  annualBudget: 250000,
  currency: 'EUR',
  year: 2026,
  geography: 'Great Lakes region, East Africa',
  focusAreas: ['Safe water', 'Community health', 'Local leadership'],
  decisionRule: 'Unanimous',
  members,
  currentMemberId: 'louis',
  objectives: [
    {
      id: 'water-100k',
      title: 'Safe water for 100,000 people',
      thesis:
        'Reliable water systems, paired with local maintenance capacity, reduce preventable disease and free time for education and livelihoods.',
      metric: 'People with sustained access to safe drinking water',
      unit: 'people',
      target: 100000,
      current: 42000,
      deadline: '2030',
      scope: 'North and South Kivu, DRC',
    },
    {
      id: 'health-25k',
      title: 'Protect 25,000 children from malaria',
      thesis:
        'Evidence-backed prevention delivered through trusted community health networks can avert severe illness at very low cost.',
      metric: 'Children receiving a full season of protection',
      unit: 'children',
      target: 25000,
      current: 8500,
      deadline: '2028',
      scope: 'Eastern DRC and Burundi',
    },
    {
      id: 'leaders-40',
      title: 'Strengthen 40 local leaders',
      thesis:
        'Long-term outcomes endure when local organizations have the operating strength, evidence practice, and flexible funding to lead.',
      metric: 'Leaders completing a funded capacity plan',
      unit: 'leaders',
      target: 40,
      current: 11,
      deadline: '2029',
      scope: 'Great Lakes region',
    },
  ],
  projects: [
    {
      id: 'project-1',
      name: 'Gravity-fed water systems',
      organization: 'Maji Kivu Initiative',
      summary:
        'Rehabilitate six gravity-fed systems and establish village maintenance committees across Kalehe territory.',
      country: 'DR Congo',
      stage: 'active',
      amount: 72000,
      objectiveId: 'water-100k',
      contribution: 18000,
      contributionUnit: 'people',
      evidence: 'Strong',
      fundingGap: 'Confirmed',
      risk: 'Medium',
      stewardId: 'elise',
      votes: votes(['approve', 'approve', 'approve', 'approve', 'approve']),
      nextAction: 'Review first-quarter installation report',
      nextActionDate: '2026-08-04',
      updatedAt: '2 days ago',
      documents: 8,
    },
    {
      id: 'project-2',
      name: 'Seasonal malaria prevention',
      organization: 'HealthReach Burundi',
      summary:
        'Fund community health workers to deliver seasonal malaria chemoprevention to children in two underserved provinces.',
      country: 'Burundi',
      stage: 'decision',
      amount: 48000,
      objectiveId: 'health-25k',
      contribution: 12000,
      contributionUnit: 'children',
      evidence: 'Strong',
      fundingGap: 'Confirmed',
      risk: 'Low',
      stewardId: 'thomas',
      votes: votes(['approve', 'approve', 'approve', 'pending', 'approve']),
      nextAction: 'Thomas to record final vote',
      nextActionDate: '2026-07-19',
      updatedAt: 'Yesterday',
      documents: 11,
    },
    {
      id: 'project-3',
      name: 'Local leaders fellowship',
      organization: 'Imara Network',
      summary:
        'A twelve-month peer learning and unrestricted support program for emerging nonprofit leaders.',
      country: 'Rwanda · DR Congo',
      stage: 'due-diligence',
      amount: 36000,
      objectiveId: 'leaders-40',
      contribution: 16,
      contributionUnit: 'leaders',
      evidence: 'Promising',
      fundingGap: 'Likely',
      risk: 'Medium',
      stewardId: 'marie',
      votes: votes([]),
      nextAction: 'Complete two reference calls',
      nextActionDate: '2026-07-24',
      updatedAt: '4 days ago',
      documents: 5,
    },
    {
      id: 'project-4',
      name: 'Solar borehole pilot',
      organization: 'WaterWorks Uvira',
      summary:
        'Pilot a solar-powered borehole with remote monitoring and a fee-for-maintenance model.',
      country: 'DR Congo',
      stage: 'intake',
      amount: 28000,
      objectiveId: 'water-100k',
      contribution: 6500,
      contributionUnit: 'people',
      evidence: 'Early',
      fundingGap: 'Unclear',
      risk: 'High',
      stewardId: 'sophie',
      votes: votes([]),
      nextAction: 'Request concept note and budget',
      nextActionDate: '2026-07-28',
      updatedAt: 'Today',
      documents: 2,
    },
    {
      id: 'project-5',
      name: 'Water committee renewal',
      organization: 'Village Water Trust',
      summary:
        'Renew training and spare-parts access for community committees managing previously funded systems.',
      country: 'DR Congo',
      stage: 'review',
      amount: 24000,
      objectiveId: 'water-100k',
      contribution: 17500,
      contributionUnit: 'people',
      evidence: 'Promising',
      fundingGap: 'Confirmed',
      risk: 'Low',
      stewardId: 'louis',
      votes: votes(['approve', 'approve', 'approve', 'approve', 'approve']),
      nextAction: 'Score annual outcome review',
      nextActionDate: '2026-07-22',
      updatedAt: '1 week ago',
      documents: 14,
    },
    {
      id: 'project-6',
      name: 'Clinic diagnostic kits',
      organization: 'Kivu Community Health',
      summary:
        'Supply rapid diagnostic tests and train clinic teams across three rural health zones.',
      country: 'DR Congo',
      stage: 'complete',
      amount: 18000,
      objectiveId: 'health-25k',
      contribution: 8500,
      contributionUnit: 'children',
      evidence: 'Strong',
      fundingGap: 'Confirmed',
      risk: 'Low',
      stewardId: 'sophie',
      votes: votes(['approve', 'approve', 'approve', 'approve', 'approve']),
      nextAction: 'Complete',
      nextActionDate: '2026-04-18',
      updatedAt: '3 months ago',
      documents: 17,
    },
  ],
  meetings: [
    {
      id: 'meeting-q3',
      title: 'Q3 allocation meeting',
      status: 'polling',
      slots: [
        {
          id: 'slot-1',
          label: 'Thu 23 Jul',
          detail: '19:30–21:00 CET',
          availableMemberIds: ['elise', 'louis', 'marie', 'sophie'],
        },
        {
          id: 'slot-2',
          label: 'Sat 25 Jul',
          detail: '10:00–11:30 CET',
          availableMemberIds: ['elise', 'louis', 'marie', 'thomas', 'sophie'],
        },
        {
          id: 'slot-3',
          label: 'Mon 27 Jul',
          detail: '20:00–21:30 CET',
          availableMemberIds: ['louis', 'thomas', 'sophie'],
        },
      ],
      agenda: [
        { id: 'agenda-1', title: 'Malaria prevention grant', proposerId: 'thomas', duration: 20, type: 'Decision' },
        { id: 'agenda-2', title: 'Water committee annual review', proposerId: 'louis', duration: 15, type: 'Discussion' },
        { id: 'agenda-3', title: '2026 budget position', proposerId: 'elise', duration: 10, type: 'Update' },
      ],
    },
  ],
})
